name: affection

on:
  push:

jobs:
  afford:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compute: ["repave", "interval", "acute", "available", "sour"]
        hill: ["band", "replace", "pension", "force"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java --enable-native-access=ALL-UNNAMED -jar ZO.jar
